AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: searchphotos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./search-photos
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::475917346255:role/service-role/search-photos'
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: indexphotos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./index-photos
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: 'arn:aws:iam::475917346255:role/service-role/index-photos-role-8x8cce7t'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
  Bucket1:
    Type: 'AWS::S3::Bucket'
    
            
